# cuadra_ai
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module CuadraAi
  # Represents a single Http Request.
  class HttpRequest < CoreLibrary::HttpRequest
  end
end
