# cuadra_ai
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module CuadraAi
  # Http response received.
  class HttpResponse < CoreLibrary::HttpResponse
  end
end
