# cuadra_ai
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module CuadraAi
  # ChatController
  class ChatController < BaseController
    # This endpoint creates a new chat interaction with our AI Models.
    # @param [Chat] body Required parameter: TODO: type description here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def chat(body)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/chat',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(Single.new('OAuth2')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ChatResponseEx.method(:from_hash))
                    .is_api_response(true)
                    .local_error('400',
                                 'Bad request, read again our documentation or contact support'\
                                  ' for guidance.',
                                 ErrorResponseException)
                    .local_error('401',
                                 'Not authorized, check our OAuth2 doc.',
                                 ErrorResponseException)
                    .local_error('500',
                                 'Internal error, if this error persist, please contact support'\
                                  '.',
                                 ErrorResponseException))
        .execute
    end
  end
end
